#spring:
#  application:
#    name: diagnostic-tool
#
#  # Database Configuration
#  datasource:
#    url: jdbc:h2:file:./data/diagnostic_db
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  # H2 Console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
#
#  # JPA/Hibernate
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

spring:
  # Настройки статических ресурсов
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
    
  # Настройки Thymeleaf
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  # Настройки базы данных
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: false
    baseline-version: 1
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  security:
    user:
      name: user
      password: password
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Настройки логирования
logging:
  level:
    org:
      springframework:
        web: DEBUG
        thymeleaf: DEBUG
      thymeleaf: TRACE
    org.flywaydb: TRACE
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8090
  servlet:
    context-path: /

# Disable security
security:
  basic:
    enabled: false
  oauth2:
    client:
      registration:
        github:
          client-id:
          client-secret:
        google:
          client-id:
          client-secret:
  user:
    name: user
    password: password
