-- Initial schema for Diagnostic Tool (cleaned)
-- Target: minimal tables/columns actually used by the application code

SET
REFERENTIAL_INTEGRITY FALSE;

-- Device categories
CREATE TABLE device_categories
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    description    TEXT,
    gost_reference VARCHAR(255)
);

-- Devices
CREATE TABLE devices
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL UNIQUE,
    description       TEXT,
    category_id       BIGINT       NOT NULL,
    channel_count     INT          NOT NULL DEFAULT 1,
    architecture_type VARCHAR(20)  NOT NULL DEFAULT 'ONE_OUT_OF_ONE',
    CONSTRAINT fk_devices_category
        FOREIGN KEY (category_id) REFERENCES device_categories (id) ON DELETE CASCADE
);

-- Diagnostic methods
CREATE TABLE diagnostic_methods
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_category_id        BIGINT        NOT NULL,
    device_id                 BIGINT       NOT NULL,
    name                      VARCHAR(255)  NOT NULL,
    description               TEXT,
    coverage_level            VARCHAR(20)   NOT NULL,
    coverage_percent          NUMERIC(5, 2) NOT NULL DEFAULT 0.0,
    effectiveness             VARCHAR(20)   NOT NULL,
    suitability               VARCHAR(20)   NOT NULL DEFAULT 'MEDIUM',
    implementation_complexity VARCHAR(20)   NOT NULL,
    gost_reference            VARCHAR(255),
    CONSTRAINT fk_diagnostic_methods_device_category
        FOREIGN KEY (device_category_id) REFERENCES device_categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_diagnostic_methods_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE
);

-- Profiles
CREATE TABLE profiles
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255) NOT NULL UNIQUE,
    description               TEXT,
    architecture_type         VARCHAR(20)  NOT NULL DEFAULT 'ONE_OUT_OF_ONE',
    test_interval_days        INT,
    total_diagnostic_coverage NUMERIC(5, 2)         DEFAULT 0.00,
    is_compliant              BOOLEAN               DEFAULT FALSE,
    pfd_avg                   DOUBLE PRECISION,
    pfd_max                   DOUBLE PRECISION,
    sil_level                 INT,
    CONSTRAINT chk_profiles_architecture_type
        CHECK (architecture_type IN ('ONE_OUT_OF_ONE', 'ONE_OUT_OF_TWO', 'TWO_OUT_OF_THREE')),
    CONSTRAINT chk_profiles_diagnostic_coverage
        CHECK (total_diagnostic_coverage >= 0 AND total_diagnostic_coverage <= 100)
);

-- Profile <-> Devices (many-to-many)
CREATE TABLE profile_devices
(
    profile_id BIGINT NOT NULL,
    device_id  BIGINT NOT NULL,
    PRIMARY KEY (profile_id, device_id),
    CONSTRAINT fk_profile_devices_profile
        FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_devices_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE
);

-- Device <-> Diagnostic methods (many-to-many join table only)
CREATE TABLE device_diagnostic_methods
(
    device_id            BIGINT NOT NULL,
    diagnostic_method_id BIGINT NOT NULL,
    PRIMARY KEY (device_id, diagnostic_method_id),
    CONSTRAINT fk_ddm_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE,
    CONSTRAINT fk_ddm_method
        FOREIGN KEY (diagnostic_method_id) REFERENCES diagnostic_methods (id) ON DELETE CASCADE
);

-- Profile <-> Device <-> Diagnostic method (selected methods inside profile)
CREATE TABLE profile_diagnostic_methods
(
    profile_id           BIGINT NOT NULL,
    device_id            BIGINT NOT NULL,
    diagnostic_method_id BIGINT NOT NULL,
    is_active            BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (profile_id, device_id, diagnostic_method_id),
    CONSTRAINT fk_pdm_profile
        FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_pdm_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE,
    CONSTRAINT fk_pdm_method
        FOREIGN KEY (diagnostic_method_id) REFERENCES diagnostic_methods (id) ON DELETE CASCADE
);

-- Fault types (linked both to category and конкретное устройство)
CREATE TABLE fault_types
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(20)  NOT NULL UNIQUE,
    name                 VARCHAR(255) NOT NULL,
    description          TEXT,
    device_category_id   BIGINT       NOT NULL,
    device_id            BIGINT       NOT NULL,
    coverage_requirement VARCHAR(10)  NOT NULL CHECK (coverage_requirement IN ('LOW', 'MEDIUM', 'HIGH')),
    gost_reference       VARCHAR(100),
    CONSTRAINT fk_fault_types_device_category
        FOREIGN KEY (device_category_id) REFERENCES device_categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_fault_types_device
        FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE
);

-- Diagnostic method <-> fault type links
CREATE TABLE diagnostic_method_faults
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnostic_method_id BIGINT      NOT NULL,
    fault_type_id        BIGINT      NOT NULL,
    effectiveness        VARCHAR(10) NOT NULL CHECK (effectiveness IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT uk_diagnostic_method_fault UNIQUE (diagnostic_method_id, fault_type_id),
    CONSTRAINT fk_dmf_method
        FOREIGN KEY (diagnostic_method_id) REFERENCES diagnostic_methods (id) ON DELETE CASCADE,
    CONSTRAINT fk_dmf_fault
        FOREIGN KEY (fault_type_id) REFERENCES fault_types (id) ON DELETE CASCADE
);

-- Profile <-> fault type status/coverage info
CREATE TABLE profile_faults
(
    profile_id          BIGINT NOT NULL,
    fault_type_id       BIGINT NOT NULL,
    is_covered          BOOLEAN DEFAULT FALSE,
    covered_methods_ids TEXT,
    notes               TEXT,
    PRIMARY KEY (profile_id, fault_type_id),
    CONSTRAINT fk_pf_profile
        FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_pf_fault
        FOREIGN KEY (fault_type_id) REFERENCES fault_types (id) ON DELETE CASCADE
);

CREATE INDEX idx_fault_types_device ON fault_types (device_id);
CREATE INDEX idx_fault_types_device_category ON fault_types (device_category_id);
CREATE INDEX idx_diagnostic_method_faults_method ON diagnostic_method_faults (diagnostic_method_id);
CREATE INDEX idx_diagnostic_method_faults_fault ON diagnostic_method_faults (fault_type_id);
CREATE INDEX idx_profile_faults_profile ON profile_faults (profile_id);
CREATE INDEX idx_profile_faults_fault ON profile_faults (fault_type_id);

SET
REFERENTIAL_INTEGRITY TRUE;


